[package]
name = "lanta"
version = "0.1.0"
edition = "2021"
description = "Beautiful Lanta."
repository = "https://github.com/wnanbei/lanta"
readme = "README.md"
license = "MIT"
authors = ["wnanbei <wnanbei@gmail.com>"]

[dependencies]
